"""String(255) for hashed_password

Revision ID: ff66c32c2d62
Revises: 3db203853935
Create Date: 2026-03-23 19:20:07.849331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff66c32c2d62'
down_revision: Union[str, Sequence[str], None] = '3db203853935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
                    type_=sa.String(255))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
                    type_=sa.String())
    # ### end Alembic commands ###
